# Generated by Django 4.0.8 on 2023-05-19 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_start', models.IntegerField()),
                ('place_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('tag', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ontology_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedMaterial',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parsed_material', serialize=False, to='db_materials.material')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('html_file', models.FileField(upload_to='html_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ClassifiedOccurrence',
            fields=[
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='classified_occurrence', serialize=False, to='automations.occurrence')),
                ('occurrence_type', models.CharField(choices=[('definition', 'definition'), ('example', 'example'), ('distinction', 'distinction'), ('other', 'other')], max_length=255)),
                ('relevance', models.FloatField()),
                ('is_approved', models.BooleanField(default=False)),
                ('default_for_section', models.BooleanField(default=False)),
                ('distinction_ontology_term', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedMaterialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('parsed_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_material_sections', to='automations.parsedmaterial')),
                ('super_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parsed_material_subsections', to='automations.parsedmaterialsection')),
            ],
        ),
        migrations.CreateModel(
            name='OntologyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_topics', to='automations.ontology')),
                ('super_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ontology_subtopics', to='automations.ontologytopic')),
            ],
        ),
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('symbols', models.TextField(blank=True, null=True)),
                ('ontology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_terms', to='automations.ontology')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_terms', to='automations.ontologytopic')),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='ontology_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.ontologyterm'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='parsed_material_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='automations.parsedmaterialsection'),
        ),
        migrations.AddConstraint(
            model_name='parsedmaterialsection',
            constraint=models.UniqueConstraint(fields=('topic', 'parsed_material'), name='unique_topic_parsed_material_combination'),
        ),
        migrations.AddConstraint(
            model_name='ontologytopic',
            constraint=models.UniqueConstraint(fields=('name', 'ontology'), name='unique_name_ontology_combination'),
        ),
        migrations.AddConstraint(
            model_name='ontologyterm',
            constraint=models.UniqueConstraint(fields=('term', 'ontology'), name='unique_term_ontology_combination'),
        ),
        migrations.AddField(
            model_name='cousage',
            name='classified_occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_usages', to='automations.classifiedoccurrence'),
        ),
    ]
