# Generated by Django 4.0.8 on 2023-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='piece_of_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
