# Generated by Django 4.0.8 on 2023-05-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_occurrence_piece_of_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='piece_of_text',
        ),
    ]
