# Generated by Django 4.0.8 on 2023-05-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_remove_occurrence_piece_of_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmaterialsection',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
