# Generated by Django 4.0.8 on 2023-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_parsedmaterialsection_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occurrence',
            constraint=models.UniqueConstraint(fields=('parsed_material_section', 'ontology_term', 'place_start', 'place_end'), name='unique_parsed_material_section_ontology_term_place_start_place_end_combination'),
        ),
    ]
