# Generated by Django 4.0.8 on 2023-05-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_occurrence_unique_parsed_material_section_ontology_term_place_start_place_end_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyterm',
            name='dimension',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
