# Generated by Django 4.0.8 on 2023-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_alter_occurrence_ontology_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedoccurrence',
            name='snippet',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
