# Generated by Django 4.0.8 on 2023-05-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_alter_classifiedoccurrence_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='matched_tokens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='text_in_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
