# Generated by Django 4.0.8 on 2023-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0010_occurrence_matched_tokens_occurrence_text_in_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontologyterm',
            name='dimension',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
