# Generated by Django 4.0.8 on 2023-05-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0011_alter_ontologyterm_dimension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='matched_tokens',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='text_in_content',
        ),
    ]
