# Generated by Django 4.0.8 on 2023-05-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0012_remove_occurrence_matched_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedOccurrenceViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('snippet', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('ontology_term', models.CharField(max_length=255)),
                ('distinction_ontology_term', models.CharField(blank=True, max_length=255, null=True)),
                ('relevance', models.FloatField()),
                ('is_approved', models.BooleanField()),
                ('default_for_section', models.BooleanField()),
            ],
        ),
    ]
