# Generated by Django 4.0.8 on 2023-05-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0013_classifiedoccurrenceviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassifiedOccurrenceViewModel',
        ),
    ]
